/**
 * @fileoverview gRPC-Web generated client stub for GameSessionManager
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.1
// source: GameSessionService.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.GameSessionManager = require('./GameSessionService_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.GameSessionManager.GameSessionManagerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.GameSessionManager.GameSessionManagerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.GameSessionManager.GameSessionRequest,
 *   !proto.GameSessionManager.GameSessionResponse>}
 */
const methodDescriptor_GameSessionManager_GameTurn = new grpc.web.MethodDescriptor(
  '/GameSessionManager.GameSessionManager/GameTurn',
  grpc.web.MethodType.UNARY,
  proto.GameSessionManager.GameSessionRequest,
  proto.GameSessionManager.GameSessionResponse,
  /**
   * @param {!proto.GameSessionManager.GameSessionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.GameSessionManager.GameSessionResponse.deserializeBinary
);


/**
 * @param {!proto.GameSessionManager.GameSessionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.GameSessionManager.GameSessionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.GameSessionManager.GameSessionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.GameSessionManager.GameSessionManagerClient.prototype.gameTurn =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/GameSessionManager.GameSessionManager/GameTurn',
      request,
      metadata || {},
      methodDescriptor_GameSessionManager_GameTurn,
      callback);
};


/**
 * @param {!proto.GameSessionManager.GameSessionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.GameSessionManager.GameSessionResponse>}
 *     Promise that resolves to the response
 */
proto.GameSessionManager.GameSessionManagerPromiseClient.prototype.gameTurn =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/GameSessionManager.GameSessionManager/GameTurn',
      request,
      metadata || {},
      methodDescriptor_GameSessionManager_GameTurn);
};


module.exports = proto.GameSessionManager;

